sudo: true
language: cpp

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
  - sudo make install
  - cd ..
  - sudo cp includes/clibars.hpp /usr/include/clibars.hpp

script:
  - g++ example.cpp -o example -lclibars
  - ./example
